######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 5 16:57:11 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ODoc.h
FORMS += ODoc.ui
SOURCES += main.cpp ODoc.cpp
