######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 6 16:13:41 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ODoc.h
FORMS += ODoc.ui
SOURCES += main.cpp ODoc.cpp
