######################################################################
# Automatically generated by qmake (2.01a) mar jun 26 10:20:48 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ODictionary.h
SOURCES += main.cpp ODictionary.cpp
