######################################################################
# Automatically generated by qmake (2.01a) mar ene 29 20:37:22 2008
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += OJohnGui/
#include(OJhonGui/OJhonGui.pro)
